name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build package
        run: |
          VERSION=${{ github.event.release.tag_name }} docker-compose up -d --build
      - name: check file exists
        run: |
          ls -alR
          if [ ! -f "./build/shreyam-do_${{ github.event.release.tag_name }}.deb" ]; then
            echo "Package not found"
            exit 1
          else
            echo "Package found"
          fi
      - name: Upload package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/shreyam-do_${{ github.event.release.tag_name }}.deb
          asset_name: shreyam-do_${{ github.event.release.tag_name }}.deb
          asset_content_type: application/vnd.debian.binary-package
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      # - name: Upload Snap package
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ github.event.release.upload_url }}
      #     asset_path: ./shreyam-do_*.snap
      #     asset_name: shreyam-do_${{ github.event.release.tag_name }}.snap
      #     asset_content_type: application/snap
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}